# 送信されるメッセージのデフォルトの言語。これにはコンソールに表示される言語も含まれます。
default-locale: en_US
# かな漢字変換のデフォルト設定。trueで有効化、falseで無効化出来ます。
# クライアント側の言語を日本語に設定しているプレイヤーに適用されます。
default-japanize-enabled: true
# かな漢字変換を強制するかのデフォルト設定。trueで強制、falseで強制しません。
# クライアント側の言語を日本語にしていないプレイヤーにも強制するかどうかを設定できます。
force-japanize-enabled: false